{
 "title": "IoT Enviroment Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sensor Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\ndata =\r\n    from(bucket: \"iot_monitoring\")\r\n        |> range(start: -5d)\r\n        |> filter(fn: (r) => r.topic =~ /\\/status$/)\r\n        |> filter(fn: (r) =>\r\n            r._field == \"device_id\" or\r\n            r._field == \"status\" or\r\n            r._field == \"timestamp\"\r\n        )\r\n        |> group(columns: [\"topic\"])\r\n\r\npivoted =\r\n    data\r\n        |> pivot(\r\n            rowKey: [\"topic\"],\r\n            columnKey: [\"_field\"],\r\n            valueColumn: \"_value\"\r\n        )\r\n\r\npivoted\r\n    |> map(fn: (r) => ({\r\n        device_id: r.device_id,\r\n        status:    r.status,\r\n        last_seen: r.timestamp\r\n    }))\r\n    |> keep(columns: [\"device_id\", \"status\", \"last_seen\"])\r\n"
    }
   ]
  },
  {
   "title": "Factory Humidity Sensors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_monitoring\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r.topic =~ /^iiot\\/group\\/[^\\/]+\\/sensor\\/humidity$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"topic\"])"
    }
   ]
  },
  {
   "title": "Factory Temperature Sensors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"iot_monitoring\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r.topic =~ /^iiot\\/group\\/[^\\/]+\\/sensor\\/temperature$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"topic\"])"
    }
   ]
  },
  { "title": "Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } }
 ]
}